"""add period_logs table

Revision ID: 089238aafad2
Revises: a9e173ea39be
Create Date: 2026-02-12 11:51:38.307661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089238aafad2'
down_revision: Union[str, Sequence[str], None] = 'a9e173ea39be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_log_user_id'), table_name='activities_log')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_user_name'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_activities_log_user_id'), 'activities_log', ['user_id'], unique=False)
    # ### end Alembic commands ###
