"""add username and link activities to user

Revision ID: 219a5e26b597
Revises: e470120def05
Create Date: 2026-01-23 15:29:32.204765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219a5e26b597'
down_revision: Union[str, Sequence[str], None] = 'e470120def05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'activities_log', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('user_name', sa.String(), nullable=True))
    op.alter_column('user', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.alter_column('user', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'user_name')
    op.drop_constraint(None, 'activities_log', type_='foreignkey')
    op.alter_column('activities_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
