"""add period_logs table

Revision ID: a56f9c6bab1a
Revises: 089238aafad2
Create Date: 2026-02-12 11:56:14.736333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56f9c6bab1a'
down_revision: Union[str, Sequence[str], None] = '089238aafad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('period_length_days', sa.Integer(), nullable=True),
    sa.Column('cycle_length_days', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_logs_start_date'), 'period_logs', ['start_date'], unique=False)
    op.create_index(op.f('ix_period_logs_user_id'), 'period_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_logs_user_id'), table_name='period_logs')
    op.drop_index(op.f('ix_period_logs_start_date'), table_name='period_logs')
    op.drop_table('period_logs')
    # ### end Alembic commands ###
