"""initial schema

Revision ID: e470120def05
Revises: 
Create Date: 2026-01-17 22:24:42.757164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e470120def05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_log_activity_date'), 'activities_log', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activities_log_activity_type'), 'activities_log', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_log_user_id'), 'activities_log', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('cycle_length_days', sa.Integer(), nullable=False),
    sa.Column('period_length_days', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_activities_log_user_id'), table_name='activities_log')
    op.drop_index(op.f('ix_activities_log_activity_type'), table_name='activities_log')
    op.drop_index(op.f('ix_activities_log_activity_date'), table_name='activities_log')
    op.drop_table('activities_log')
    # ### end Alembic commands ###
